---
title: "Example Plots with ggsurvey"
output:
  html_document: default
  html_notebook: default
---


```{r, message = FALSE}
library(ggsurvey)
data(qol)
```

```{r, message = FALSE}
dstrat <- svydesign(id=~1, strata=~camp, weights=~adult_weight, data = qol, fpc=~fpc)
tab <- svymean(~prs,dstrat,na.rm=TRUE)
data.frame(tab)
gg.svystat(tab, 'prs', basic = TRUE) + geom_bar(stat = 'identity')
```

```{r, message = FALSE}
pal <- gg.svy.colors.manual()
gg.svystat(tab, 'prs', color = pal, percent = TRUE) + 
  ggtitle('\nPalestinian Refugees from Syria (PRS)\n') + 
  ylab('Percent\n') + scale_y_continuous(limits=c(0,100))
```

```{r, message=FALSE,warning=FALSE}
gg.svystat(tab,"prs", percent = TRUE, color='red')
```

```{r, message = FALSE}
tab <- svyby(~i_outdoor, ~prs, dstrat, svymean, na.rm=TRUE)
gg.svyby(tab, color = pal, percent = TRUE, legend.title = "Importance") + 
  ggtitle('\nImportance of Outdoor Activities\n') + 
  ylab('Percent\n') + xlab('\nPRS Status')
```

```{r, message = FALSE}
tab <- svyby(~prs, ~camp, dstrat, svymean, na.rm=TRUE)
gg.svyby(tab, color = pal, percent = TRUE, drop.level = 'No', legend.position = 'none') + 
  ggtitle('\nPercent Adults in Each Camp PRS\n') + 
  ylab('Percent\n') + xlab('\nCamp')
```

```{r, message = FALSE}
tab <- svyby(~prs, ~camp+gender, dstrat, svymean, na.rm=TRUE)
gg.svyby(tab, color = pal, percent = TRUE, drop.level = 'No', legend.position = 'none') + 
  ggtitle('\nPercent Male and Female Adults in Each Camp PRS\n') + 
  ylab('Percent\n') + xlab('\nCamp') + facet_wrap(~gender,ncol=2)
```

```{r, message = FALSE}
tab <- svyby(~i_outdoor, ~camp+gender, dstrat, svymean, na.rm=TRUE)
gg.svyby(tab, color = pal, percent = TRUE, error.bar.bounds = TRUE) + 
  ggtitle('\nOutdoor Importance by Camp and Gender\n') + 
  ylab('Percent\n') + facet_wrap(~gender, ncol=1)
```

```{r, message = FALSE, warning=FALSE}
tab <- svyby(~i_outdoor, ~gender, dstrat, svymean, na.rm=TRUE)
gg.svyby(tab, color = pal, percent = TRUE, legend.title = "Importance") + 
  ggtitle('\nImportance of Outdoor Activities\n') + 
  ylab('Percent\n') + scale_fill_brewer(palette="Set1")
```

```{r, warning=FALSE,message=FALSE}
tab <- svyby(~i_outdoor, ~camp, dstrat, svymean, na.rm=TRUE)
gg.svy.likert(tab, color=pal, legend.position = 'right', order=TRUE, line = 9) +
  ggtitle('\nLikert Plot of Importance of Outdoors\n')
```

```{r, warning=FALSE,message=FALSE}
tab <- svyby(~i_outdoor, ~s_outdoors, dstrat, svymean, na.rm=TRUE)
gg.svy.likert(tab, color=pal, legend.position = 'right', line = 9) +
  ggtitle('\nLikert Plot of Importance by Satisfaction of Outdoors\n')
```
